---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-metalk8s-scality-com-v1alpha1-nodeartifact
  failurePolicy: Fail
  name: vnodeartifact-v1alpha1.kb.io
  rules:
  - apiGroups:
    - metalk8s.scality.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - nodeartifacts
  sideEffects: None
