apiVersion: metalk8s.scality.com/v1alpha1
kind: NodeArtifact
metadata:
  labels:
    app.kubernetes.io/name: metalk8s-registry-node-agent
    app.kubernetes.io/managed-by: kustomize
  name: nodeartifact-sample
spec:
  name: metalk8s
  version: "1.25.3"
  nodeName: k3d-k3d-agent-1
  validation:
    checksum:
      type: sha256
      value: "ce775a33b30ae640d521df1fad60868fa701707ffdc4d8b4ca7ab60edfd05c26"
