//go:build !ignore_autogenerated

/*
Copyright 2025 Scality.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSolutionArchive) DeepCopyInto(out *NodeSolutionArchive) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSolutionArchive.
func (in *NodeSolutionArchive) DeepCopy() *NodeSolutionArchive {
	if in == nil {
		return nil
	}
	out := new(NodeSolutionArchive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSolutionArchive) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSolutionArchiveChecksum) DeepCopyInto(out *NodeSolutionArchiveChecksum) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSolutionArchiveChecksum.
func (in *NodeSolutionArchiveChecksum) DeepCopy() *NodeSolutionArchiveChecksum {
	if in == nil {
		return nil
	}
	out := new(NodeSolutionArchiveChecksum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSolutionArchiveList) DeepCopyInto(out *NodeSolutionArchiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSolutionArchive, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSolutionArchiveList.
func (in *NodeSolutionArchiveList) DeepCopy() *NodeSolutionArchiveList {
	if in == nil {
		return nil
	}
	out := new(NodeSolutionArchiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSolutionArchiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSolutionArchiveSpec) DeepCopyInto(out *NodeSolutionArchiveSpec) {
	*out = *in
	out.Validation = in.Validation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSolutionArchiveSpec.
func (in *NodeSolutionArchiveSpec) DeepCopy() *NodeSolutionArchiveSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSolutionArchiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSolutionArchiveStatus) DeepCopyInto(out *NodeSolutionArchiveStatus) {
	*out = *in
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSolutionArchiveStatus.
func (in *NodeSolutionArchiveStatus) DeepCopy() *NodeSolutionArchiveStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSolutionArchiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionArchiveValidation) DeepCopyInto(out *SolutionArchiveValidation) {
	*out = *in
	out.Checksum = in.Checksum
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionArchiveValidation.
func (in *SolutionArchiveValidation) DeepCopy() *SolutionArchiveValidation {
	if in == nil {
		return nil
	}
	out := new(SolutionArchiveValidation)
	in.DeepCopyInto(out)
	return out
}
