//go:build go1.22

// Package intern provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package intern

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// AdditionalInformation A map containing flexible metadata or contextual details about the error.
	AdditionalInformation *map[string]interface{} `json:"additionalInformation,omitempty"`

	// Code An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetails

// Forbidden defines model for Forbidden.
type Forbidden = ProblemDetails

// NotFound defines model for NotFound.
type NotFound = ProblemDetails

// ServerError defines model for ServerError.
type ServerError = ProblemDetails

// Unauthorized defines model for Unauthorized.
type Unauthorized = ProblemDetails

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ProblemDetails

// DownloadSolutionArchiveParams defines parameters for DownloadSolutionArchive.
type DownloadSolutionArchiveParams struct {
	// Range Range of the chunk to serve. Must respect the format `bytes=<start-index>-<end-index>`
	Range string `json:"Range"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DownloadSolutionArchive request
	DownloadSolutionArchive(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DescribeSolutionArchive request
	DescribeSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DownloadSolutionArchive(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadSolutionArchiveRequest(c.Server, solutionArchive, version, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DescribeSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDescribeSolutionArchiveRequest(c.Server, solutionArchive, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDownloadSolutionArchiveRequest generates requests for DownloadSolutionArchive
func NewDownloadSolutionArchiveRequest(server string, solutionArchive string, version string, params *DownloadSolutionArchiveParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "solutionArchive", runtime.ParamLocationPath, solutionArchive)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/downloads/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Range", runtime.ParamLocationHeader, params.Range)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Range", headerParam0)

	}

	return req, nil
}

// NewDescribeSolutionArchiveRequest generates requests for DescribeSolutionArchive
func NewDescribeSolutionArchiveRequest(server string, solutionArchive string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "solutionArchive", runtime.ParamLocationPath, solutionArchive)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/downloads/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DownloadSolutionArchiveWithResponse request
	DownloadSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*DownloadSolutionArchiveResponse, error)

	// DescribeSolutionArchiveWithResponse request
	DescribeSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DescribeSolutionArchiveResponse, error)
}

type DownloadSolutionArchiveResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON422 *UnprocessableEntity
	ApplicationproblemJSON500 *ServerError
}

// Status returns HTTPResponse.Status
func (r DownloadSolutionArchiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadSolutionArchiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DescribeSolutionArchiveResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON500 *ServerError
}

// Status returns HTTPResponse.Status
func (r DescribeSolutionArchiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DescribeSolutionArchiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DownloadSolutionArchiveWithResponse request returning *DownloadSolutionArchiveResponse
func (c *ClientWithResponses) DownloadSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*DownloadSolutionArchiveResponse, error) {
	rsp, err := c.DownloadSolutionArchive(ctx, solutionArchive, version, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadSolutionArchiveResponse(rsp)
}

// DescribeSolutionArchiveWithResponse request returning *DescribeSolutionArchiveResponse
func (c *ClientWithResponses) DescribeSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DescribeSolutionArchiveResponse, error) {
	rsp, err := c.DescribeSolutionArchive(ctx, solutionArchive, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDescribeSolutionArchiveResponse(rsp)
}

// ParseDownloadSolutionArchiveResponse parses an HTTP response from a DownloadSolutionArchiveWithResponse call
func ParseDownloadSolutionArchiveResponse(rsp *http.Response) (*DownloadSolutionArchiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadSolutionArchiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseDescribeSolutionArchiveResponse parses an HTTP response from a DescribeSolutionArchiveWithResponse call
func ParseDescribeSolutionArchiveResponse(rsp *http.Response) (*DescribeSolutionArchiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DescribeSolutionArchiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Download the solution archive.
	// (GET /downloads/{solutionArchive}/{version})
	DownloadSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string, params DownloadSolutionArchiveParams)
	// Describe the solution archive.
	// (HEAD /downloads/{solutionArchive}/{version})
	DescribeSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DownloadSolutionArchive operation middleware
func (siw *ServerInterfaceWrapper) DownloadSolutionArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "solutionArchive" -------------
	var solutionArchive string

	err = runtime.BindStyledParameterWithOptions("simple", "solutionArchive", r.PathValue("solutionArchive"), &solutionArchive, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "solutionArchive", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadSolutionArchiveParams

	headers := r.Header

	// ------------- Required header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = Range

	} else {
		err := fmt.Errorf("Header parameter Range is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Range", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadSolutionArchive(w, r, solutionArchive, version, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DescribeSolutionArchive operation middleware
func (siw *ServerInterfaceWrapper) DescribeSolutionArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "solutionArchive" -------------
	var solutionArchive string

	err = runtime.BindStyledParameterWithOptions("simple", "solutionArchive", r.PathValue("solutionArchive"), &solutionArchive, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "solutionArchive", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DescribeSolutionArchive(w, r, solutionArchive, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/downloads/{solutionArchive}/{version}", wrapper.DownloadSolutionArchive)
	m.HandleFunc("HEAD "+options.BaseURL+"/downloads/{solutionArchive}/{version}", wrapper.DescribeSolutionArchive)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse ProblemDetails

type ForbiddenApplicationProblemPlusJSONResponse ProblemDetails

type NotFoundApplicationProblemPlusJSONResponse ProblemDetails

type ServerErrorApplicationProblemPlusJSONResponse ProblemDetails

type UnauthorizedApplicationProblemPlusJSONResponse ProblemDetails

type UnprocessableEntityApplicationProblemPlusJSONResponse ProblemDetails

type DownloadSolutionArchiveRequestObject struct {
	SolutionArchive string `json:"solutionArchive"`
	Version         string `json:"version"`
	Params          DownloadSolutionArchiveParams
}

type DownloadSolutionArchiveResponseObject interface {
	VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error
}

type DownloadSolutionArchive206ResponseHeaders struct {
	ContentDigest string
	ContentRange  string
}

type DownloadSolutionArchive206ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadSolutionArchive206ResponseHeaders
	ContentLength int64
}

func (response DownloadSolutionArchive206ApplicationoctetStreamResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Digest", fmt.Sprint(response.Headers.ContentDigest))
	w.Header().Set("Content-Range", fmt.Sprint(response.Headers.ContentRange))
	w.WriteHeader(206)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadSolutionArchive400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive400ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive401ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive403ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive404ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive422ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive500ApplicationProblemPlusJSONResponse struct {
	ServerErrorApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive500ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchiveRequestObject struct {
	SolutionArchive string `json:"solutionArchive"`
	Version         string `json:"version"`
}

type DescribeSolutionArchiveResponseObject interface {
	VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error
}

type DescribeSolutionArchive200ResponseHeaders struct {
	ContentLength int64
}

type DescribeSolutionArchive200Response struct {
	Headers DescribeSolutionArchive200ResponseHeaders
}

func (response DescribeSolutionArchive200Response) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.WriteHeader(200)
	return nil
}

type DescribeSolutionArchive400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive400ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive401ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive403ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive404ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive500ApplicationProblemPlusJSONResponse struct {
	ServerErrorApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive500ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Download the solution archive.
	// (GET /downloads/{solutionArchive}/{version})
	DownloadSolutionArchive(ctx context.Context, request DownloadSolutionArchiveRequestObject) (DownloadSolutionArchiveResponseObject, error)
	// Describe the solution archive.
	// (HEAD /downloads/{solutionArchive}/{version})
	DescribeSolutionArchive(ctx context.Context, request DescribeSolutionArchiveRequestObject) (DescribeSolutionArchiveResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DownloadSolutionArchive operation middleware
func (sh *strictHandler) DownloadSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string, params DownloadSolutionArchiveParams) {
	var request DownloadSolutionArchiveRequestObject

	request.SolutionArchive = solutionArchive
	request.Version = version
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadSolutionArchive(ctx, request.(DownloadSolutionArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadSolutionArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadSolutionArchiveResponseObject); ok {
		if err := validResponse.VisitDownloadSolutionArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DescribeSolutionArchive operation middleware
func (sh *strictHandler) DescribeSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string) {
	var request DescribeSolutionArchiveRequestObject

	request.SolutionArchive = solutionArchive
	request.Version = version

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DescribeSolutionArchive(ctx, request.(DescribeSolutionArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DescribeSolutionArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DescribeSolutionArchiveResponseObject); ok {
		if err := validResponse.VisitDescribeSolutionArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaa2/bOtL+KwTf98Me1LIVx0lbAf3QnianwWmL9LpATwuEFscWTyVSJalc4f++IKm7",
	"JV+TXWA3/VJHFufyzHA4z9B3OBRJKjhwrXBwh+GaJGkM9vNMyCmjFLj545LEGZgPFDRhMQ7w5wiQBCUy",
	"GQIKRRZTxIVGU/NUZ5IDRUQhbd/6lYHSQiKm7Dsk05GQ7BYoHmClic4UDib+4QBrpmPAAT4tdQ+wvknN",
	"IzIVmQ6mMeE/8WIxwIxfkphRbyrojZdKkYLUN95MyIRoZ6gKJUs1ExwH+COkEhRwTcwDJGaIoInvo1eE",
	"oo/OPuNNKrgCdBWBBESQEY0K0YgKcObHcAmSzME6FwopIdQoVzyokAoFNXZPfN/zJ3jQRs7ptCpCwTVh",
	"XCGCEhIbSUBLvcMGRn6F0ZkDAL0yIs4LK08LO3LYIq1TFYxGqRTTGBLlSZgzpeXNUCVE6ikQOQxFMloJ",
	"5zq8vSumIw+kFFI9Yv/vwr62J/eEW69AJdddxcKp7QH76YZg81JuM9BW6Jawf80NuhfUnVdrQL/3fH8M",
	"wIoA5B54ERAK8j5LfIGNk2xAuGQUKLoiqqoGfUgf9yHdWVLaqogkCWiQa6EuTH/jFu5bY7rBXAv3A1T4",
	"XxnIGyQMFjqqADFNQgnb8H8F/IQpxfi8uRfuCWj5K2MSKLowwi+qrW6yXCRMa6BoepOfqFxliQOmE/fn",
	"fbibqDkfTG2B6xRCK7deXHrhfpevbLy9PczdIPbC+wA5/Qh1CXUz1+8J3wsn7aJWLnaBdrwltG8+fz5v",
	"FZG1ADdf3x3hFo79ED9AOj/C3QV3CcZ9oWxPwgtzFF6Ys3BfuA+3hLvnIN4Y8gqPvVGvRK0E/iFS/TEI",
	"3UHgQnszkXG6agxkF9pGKx8IGcgMX3cr6z5MKh/e117omfIokJcgXaj7DXBvIeChyLgGcwITjjJeouvW",
	"V2Yc1aH85Faf5O/0WJLx2tiq05KXYQhKIS1+ArfOK9Amonn3N0Q9WHUOzxqYHVTGfuGN6VmvsakUxhoy",
	"jcEDrpnrJlfGr0l7jOUNy3KJrikvbRuP67bVtKITp7XHxsUAF3vQbuFXhOZ70+0kroHbjyRNYxbarVxk",
	"8pO/leDtcWWOsmGmBTE9LZni/0uY4QD/36gad46KxWvGL4N+yf9kOjopi9DOOhrVrFvf1yJuOyjJCXW/",
	"3L3dWJ6JVNryoDoCtWVAeujSKtk7+LKe71ZHUR27tQp6euROYVvYvZ7LVCoaCG0sud0DdYvbweQVDeuS",
	"kvN6l7WV9Nr51St0D+O7uxB7WIURJKRPoPtWjc5dEXttK7BypbDZwOxSk9F3/p2f5Dabnuei1u5YJmqU",
	"Ilf3y/ZHBWYZ8tBfnbzwxz/24oOj35zss85Jo9tom6tYVUJXa7L1aV9FVkihp5t1bA9Xc0O0vWiNrXYF",
	"rLPA9XlSZvfuzpQiRr+h4l+3Y1WLva9v1absTohljTsmxbLCPDFMsTmtX5nu0MM0rlxXFqXqzQcqPF23",
	"tUgLlII0CCMdMYXM1shJFs/vMFxPOzRovBf6tCAOO4DBa8tXYlExlAfCopfYWDcdfTgpGMoOnqqmhJXO",
	"NgjRffu7IY9aDJo0ZDev24RqpduNl+/T7QZpyzO+xducvzVqc1LyqZ3c7pS0xvsOOvef7jhqBljHWlqC",
	"O5yfncw5TihlRh2Jz7gr0syhU31xXlugZQZLwUIJSYsrHnNqzWK4ZoZsJqAJJZo4e7mGa52ROG93FLLc",
	"01Yom8GGwebgOuqoQRq7KA6eP3t6fFQyjFMGMVU4+AtDYvjyAN+y9HdBAf8wtDcBpUmS4gCP/fGx5x95",
	"44PP/rPgYBL4/jeTNzn3FdO/IbTUxc2I2iOrlxy9PD9DKoWQzVjorETmXUQYNZ4a2/P7SYk0kARlnIJU",
	"mnBaOYamRJmg2WrMJBJXHKXCpCgjMdLkWnCR2DFTeczhAU7I9Vvgcx3h4MgvbVZaMj7Hi2qOtWQ1irKE",
	"cE8CoZbyw3UaE+5OhNIXLfLDIgwzKYGHYNrT3B+TMS0TJv7z4w4jGDe+hl3goS8fz5CEGTjpOiIaMWqc",
	"njFwv0Eqrem3Ap1plBALjvnP5PuNCT+aZVJHYOpBmbaIzRCFUiVtuXDgjycdLhRDk7uO3Wdn3u4FF/c5",
	"cHO4ViNHIdmc8aJGz4TcANbirtyk+OHYGcmSLMHB0fPnhhxx99eBX8Xd7Ia5I0/5YGcZcBUJqQft8Kss",
	"SYi8admBjFyLrorKShJGhM8BzaRI6h5o0e/PAMF1CKn9uQ9KM5kK5ZhOLEISs1sbmM0C4R7skkcNn+oA",
	"Z5JtoNpOvdwdoSkqDt8fS2XCXcfPxLKNr8UVjwWhSIk4s5lIZBixS1AWlnegSfznM4WrodzmKy5BKqfl",
	"YOgPfQOUSIGTlOEAHw794SEe4JToyKbwiOaC1eiuEP3SSV6M7nJZC/PmHOwBWTaLpsyWZn1qLrUa8s7a",
	"1N22/+9JUuZF2yFsQMOBNREPMCeJhX5JQRUBd8ZUh+hStNrqvzq3trOgwHUvzR/tfsn1hlHGf5rNYovB",
	"EL3L8isNCN0p59ISXUxvNKgX3zPfPwyVJlJ7jFO4tg/Ac8+B0/rTi/rZiJ0A3xsXrpX3a7lz1q6tXPvR",
	"mvyO/eMVrZQINWhPaQkksb1yKbfcelPGiawNmktNS22Oymy3N8tiQwTtmVioHeSeWZN+dw+912yeD6SX",
	"Cza13zUiMkCviILjiW2gqZ3P98NSYawi4o2Pjl8EdHJ49EE84X9+ezJ/G355w5/+8UF/eDqO2KuvL+e/",
	"xFv1jX87Z5//OP/5IqgXn6lVi7vKTeGKi1OnJ3I5tWxebWq/zRHke+PRpGGUfbxV7o3cUy00iT3FbsFj",
	"3LNy3PddMV4M8MT3+1rgMtNGtQsGu+Rg/ZIGybGLDtcvqmYAdsVk/YqSJ5sF4/Emdi1TiMUAH20CQ52t",
	"2gbendn1g6KrslkSZHZIRyW3CTWFx0q+Ybnzl7dhrTCV4HaXpKK9aEv4xG5LOKuxxYzFgBhHdg+tNLve",
	"KdZLSdkN/rfttH13S571fbulurx2yZ/JuHYlf3YeHPn+eERSNro8GOHFj8W/AgAA//9upoWcizEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
