//go:build go1.22

// Package intern provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package intern

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ErrorDetail An object to provide explicit details on a problem towards an API consumer.
type ErrorDetail struct {
	// Code A string containing additional provider specific codes to identify the error context.
	Code *string `json:"code,omitempty"`

	// Detail A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
	Detail string `json:"detail"`

	// Header The name of the header that is the source of error.
	Header *string `json:"header,omitempty"`

	// Parameter The name of the query or path parameter that is the source of error.
	Parameter *string `json:"parameter,omitempty"`

	// Pointer A JSON Pointer to a specific request body property that is the source of error.
	Pointer *string `json:"pointer,omitempty"`
}

// Errors An array of error details to accompany a problem details response.
type Errors = []ErrorDetail

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// Code An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors An array of error details to accompany a problem details response.
	Errors *Errors `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetails

// Forbidden defines model for Forbidden.
type Forbidden = ProblemDetails

// NotFound defines model for NotFound.
type NotFound = ProblemDetails

// ServerError defines model for ServerError.
type ServerError = ProblemDetails

// Unauthorized defines model for Unauthorized.
type Unauthorized = ProblemDetails

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DownloadSolutionArchive request
	DownloadSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DescribeSolutionArchive request
	DescribeSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DownloadSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadSolutionArchiveRequest(c.Server, solutionArchive, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DescribeSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDescribeSolutionArchiveRequest(c.Server, solutionArchive, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDownloadSolutionArchiveRequest generates requests for DownloadSolutionArchive
func NewDownloadSolutionArchiveRequest(server string, solutionArchive string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "solutionArchive", runtime.ParamLocationPath, solutionArchive)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/downloads/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDescribeSolutionArchiveRequest generates requests for DescribeSolutionArchive
func NewDescribeSolutionArchiveRequest(server string, solutionArchive string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "solutionArchive", runtime.ParamLocationPath, solutionArchive)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/downloads/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DownloadSolutionArchiveWithResponse request
	DownloadSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DownloadSolutionArchiveResponse, error)

	// DescribeSolutionArchiveWithResponse request
	DescribeSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DescribeSolutionArchiveResponse, error)
}

type DownloadSolutionArchiveResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON500 *ServerError
}

// Status returns HTTPResponse.Status
func (r DownloadSolutionArchiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadSolutionArchiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DescribeSolutionArchiveResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON500 *ServerError
}

// Status returns HTTPResponse.Status
func (r DescribeSolutionArchiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DescribeSolutionArchiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DownloadSolutionArchiveWithResponse request returning *DownloadSolutionArchiveResponse
func (c *ClientWithResponses) DownloadSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DownloadSolutionArchiveResponse, error) {
	rsp, err := c.DownloadSolutionArchive(ctx, solutionArchive, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadSolutionArchiveResponse(rsp)
}

// DescribeSolutionArchiveWithResponse request returning *DescribeSolutionArchiveResponse
func (c *ClientWithResponses) DescribeSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DescribeSolutionArchiveResponse, error) {
	rsp, err := c.DescribeSolutionArchive(ctx, solutionArchive, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDescribeSolutionArchiveResponse(rsp)
}

// ParseDownloadSolutionArchiveResponse parses an HTTP response from a DownloadSolutionArchiveWithResponse call
func ParseDownloadSolutionArchiveResponse(rsp *http.Response) (*DownloadSolutionArchiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadSolutionArchiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseDescribeSolutionArchiveResponse parses an HTTP response from a DescribeSolutionArchiveWithResponse call
func ParseDescribeSolutionArchiveResponse(rsp *http.Response) (*DescribeSolutionArchiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DescribeSolutionArchiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Download the solution archive.
	// (GET /downloads/{solutionArchive}/{version})
	DownloadSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string)
	// Describe the solution archive.
	// (HEAD /downloads/{solutionArchive}/{version})
	DescribeSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DownloadSolutionArchive operation middleware
func (siw *ServerInterfaceWrapper) DownloadSolutionArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "solutionArchive" -------------
	var solutionArchive string

	err = runtime.BindStyledParameterWithOptions("simple", "solutionArchive", r.PathValue("solutionArchive"), &solutionArchive, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "solutionArchive", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadSolutionArchive(w, r, solutionArchive, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DescribeSolutionArchive operation middleware
func (siw *ServerInterfaceWrapper) DescribeSolutionArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "solutionArchive" -------------
	var solutionArchive string

	err = runtime.BindStyledParameterWithOptions("simple", "solutionArchive", r.PathValue("solutionArchive"), &solutionArchive, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "solutionArchive", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DescribeSolutionArchive(w, r, solutionArchive, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/downloads/{solutionArchive}/{version}", wrapper.DownloadSolutionArchive)
	m.HandleFunc("HEAD "+options.BaseURL+"/downloads/{solutionArchive}/{version}", wrapper.DescribeSolutionArchive)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse ProblemDetails

type ForbiddenApplicationProblemPlusJSONResponse ProblemDetails

type NotFoundApplicationProblemPlusJSONResponse ProblemDetails

type ServerErrorApplicationProblemPlusJSONResponse ProblemDetails

type UnauthorizedApplicationProblemPlusJSONResponse ProblemDetails

type DownloadSolutionArchiveRequestObject struct {
	SolutionArchive string `json:"solutionArchive"`
	Version         string `json:"version"`
}

type DownloadSolutionArchiveResponseObject interface {
	VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error
}

type DownloadSolutionArchive200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadSolutionArchive200ApplicationoctetStreamResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadSolutionArchive400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive400ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive401ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive403ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive404ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSolutionArchive500ApplicationProblemPlusJSONResponse struct {
	ServerErrorApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive500ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchiveRequestObject struct {
	SolutionArchive string `json:"solutionArchive"`
	Version         string `json:"version"`
}

type DescribeSolutionArchiveResponseObject interface {
	VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error
}

type DescribeSolutionArchive200ResponseHeaders struct {
	ContentLength int64
}

type DescribeSolutionArchive200Response struct {
	Headers DescribeSolutionArchive200ResponseHeaders
}

func (response DescribeSolutionArchive200Response) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.WriteHeader(200)
	return nil
}

type DescribeSolutionArchive400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive400ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive401ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive403ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive404ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DescribeSolutionArchive500ApplicationProblemPlusJSONResponse struct {
	ServerErrorApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive500ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Download the solution archive.
	// (GET /downloads/{solutionArchive}/{version})
	DownloadSolutionArchive(ctx context.Context, request DownloadSolutionArchiveRequestObject) (DownloadSolutionArchiveResponseObject, error)
	// Describe the solution archive.
	// (HEAD /downloads/{solutionArchive}/{version})
	DescribeSolutionArchive(ctx context.Context, request DescribeSolutionArchiveRequestObject) (DescribeSolutionArchiveResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DownloadSolutionArchive operation middleware
func (sh *strictHandler) DownloadSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string) {
	var request DownloadSolutionArchiveRequestObject

	request.SolutionArchive = solutionArchive
	request.Version = version

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadSolutionArchive(ctx, request.(DownloadSolutionArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadSolutionArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadSolutionArchiveResponseObject); ok {
		if err := validResponse.VisitDownloadSolutionArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DescribeSolutionArchive operation middleware
func (sh *strictHandler) DescribeSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string) {
	var request DescribeSolutionArchiveRequestObject

	request.SolutionArchive = solutionArchive
	request.Version = version

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DescribeSolutionArchive(ctx, request.(DescribeSolutionArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DescribeSolutionArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DescribeSolutionArchiveResponseObject); ok {
		if err := validResponse.VisitDescribeSolutionArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuBX+Kxi2D92pbraVbaM3Z2PPum1cT5JNH7KeEUQeidiQAA0c2lY8+u+dA/Au",
	"Uld76+lsXiKLxLl8536gJ89XcaIkSDTe5MmDRx4nEdjPc6VnIghA0h/3PEqBPgSAXETexPscAtNgVKp9",
	"YL5Ko4BJhWxG32KqJQSMG4b2rbsUDCrNhLHv8BRDpcV3CLyeZ5BjarzJeHTW81BgBN7Euyx49zxcJvQV",
	"n6kUJ7OIy2/eatXzhLznkQj6MxUs+4lWCWhc9udKxxydoMbXIkGhpDfxPkKiwYBETl8wNWecjUcj9o4H",
	"7KOTj7RJlDTAHkLQwDgj0iwnzQIFTvwI7kHzBVjlfKU1+Mgyxr0SKV8FJPd4NOqPxl6viZzjaVn4SiIX",
	"0jDOYh4RJQgKvoMaRqMSoysHAHtHJG5yKS9zOTLYQsTETIbDRKtZBLHpa1gIg3o5MDHXOAOuB76Khxvh",
	"3IZ3/0Fg2AetlTb/b9jnWn2t+P6H1FhP5yxRRqC4ByYkwgK01/MSRZ+1N/GGdymXKHDprW5fsxErwX2k",
	"3XADvBnv0qiObYfV/raj1WRBt+4xluiesfMlE+hZUHdabQH92QPnFRqgLYDO3WM2vaZ4nlJhKAkN2E0E",
	"3ADRuhcBsGmsJIbRcsqUZtO7lGsEHS2ntWD70zDm+hugkIufVBynUvgWtuHcCi79vaPwhd0hw7MfAg9A",
	"P2flyi3lKOcwBuyBmzLJddn9xy67t2bKJiuueQwIemvk5aL/7A4em/HawdwK9wsUrrsU9JIcNeEYloCQ",
	"ixewDV4e/LaoqxLMzjRdwn1NEer7kOD2kPnd7BgLY4Rc1MPqmWym71KhIWBTIj4tcxiho2KBCAGbLbOe",
	"Q5o0dhi3mvBtlwnJAZwOlOvgMQHf0q1mzc6w+ZCdrL29P8ztIHbC+wLh8aqg7gqSeiV7kjyGFREl+iT9",
	"oN7m0fPuSPndTFePnWey19RRm1Yy2SGmOt3TVD9//nzTyFVbY6P++uEIN3DshvgFwuN1wd0VH1nxeHJF",
	"ohYa+9SQ/4HhClify1623LvGlAr+sYY729NwHd3GzrFS4nE06iWpjcC/RNC8XiN0RZA7UorZUWNKb/V2",
	"KzIvblepsD9XqQw2bQXtQdugZvtBsoJUyNzJqg7jUofrygsdSz8D+h60855uAdxbDKSvUqrREJC5UlkY",
	"zJ0vxXhThfKTO32RvdMhSSorW8xWSSj7GcNQfQNplTeA5CTFlNuBVesutYbZSSnsL7K2TG0VdtXz8pCx",
	"EfeOB1koOceXCNJ+5EkS5VNz5iV//c0o2dwMZxrQtJwPy5fF9PpnDXM7jpeb5WF+eMuCqtdN+T8Cw4si",
	"ZxzMo5Z82vl9yQ15AJNsyO+me7Qa61ujkltmVDeJ7WmQjrlrE+0DdNk+g5eVo4rdVgYdzXErsT3k3j4U",
	"lSxqCO1MudmytJM7QOQNneoak5tqU7QX9Upt6CR6hPDtTYMtBH4IMe8i6J6a4Y1LYu9tSjYuFdb7jWp1",
	"r+1CKFPXMnGiFeVzCAbsV/mrvMhkphZlWulO7EhLTJkrBEW3YiZ0jPXZ19aB8PYvRw2Cwx8c7avWXawL",
	"tN1ZbEqhmznZ/HQsI0sk59M+JOwPVz0gmlo01mKHAtaa4Lo0Kbz7cGUKEsMfWP6vXbGy1TxWtzIo2x1i",
	"neOBTrHOMHMMSjaX1dvpA3qY2u32xqRUvvlCiaftYpyhYgloQphhKAyj0MhmIpnd8rh+cUBoXCu8zJvy",
	"A8CQleMbsSi7/xfConNosGq61vwi7/4P0NTUKWxUtjZsPLe+O84oq169xT9M6+awslHt2svPqXZtIMo8",
	"vjETVfhZwa2h3mcTVXNXcC6Zmv0GPtpgye4K4ZEgEZiVX0PhwouajOqB68BeNp7fXNU2AVn1EQ4xtw5Y",
	"48gMakrh2XWMXQQEgaDHPMpl0Mwk4Iu58BmRIY2ZCECimLsFhDWtpQGPSLxj/vgvkAsMaRQtpjjHy1uV",
	"y4h1eRaayzTimlUe5BmikMLx0xBxdJml8fOKXnMd0WtsMkyPcRkMla7sBisyj0dvf2yRumsPTe4veQzU",
	"OmG5TcSQ2w2LFd1lADV3sjf4nYxOxy38Nuz2miy7LumOlyG/FVg31T8+/fua3bjnzgiFgWpX60UvdaQw",
	"duzPlrKTr7kP3RbvudghoS86lnHnknGt+bJgWwQVie9TEuByWQmv/HHe85KYAiE225JHNc5XVrUrd+xk",
	"NCoDwgpDzxu5ZvK0W/S6oG+EBb3LuAgolgnpIogReMxSGYA2yGVQidwZNzQg2CgTmqkHyRJFOVnwiCF/",
	"VFLF1ruKBueoGA/TmMu+Bh7wWeQyHJeuFyh0QZW1Cb6fag3SL1w9s81uIQsb57SatbLNA2Hjt6bKXz5e",
	"MQ1zcNI4Z3ZZUICpJ6huqdkVsphbMOk/KhlLAVHA5qnGEKhyuC6U0BBzFkDBMtgtYvO1WlvKsNci7gXn",
	"JwuQ1IaVu2SlxULIvJrPld7BDPkvPTwh8ezUCSniNPYmb96+pTFaur9OKq6f/7xsVaz+WmpTqDT2mu5i",
	"0jjmetmQgxFdi64JiynXD7lcAJtrFVc1QNWtT4/Bow+J/Q0eS1KdKONm4kj5PBLfrWF2M4T74hA/qulU",
	"BTjVYv9E6fBdz5PuxyRztS7je/UgI8UDZlSUWk/k2g/FPRgLywdAHv3z78Yr17a7n7gHbRyXk8FoMCKg",
	"VAKSJ8KbeGeD0eDM3hNgaF14GGSEzfApJ33uKK+GTxmtFb25ANtBFmPFVVAR61P9aPUmIr/LqOp/Xams",
	"TYWoAtA7JKLXc7cYE8+sMSgtgDqFatO5Zq0m+y9Orf0kyHHdh/NtY5F+OhptaMiVj4B9gxp4bEePgm7h",
	"nzMhua78FqDgtNY7m9Q2z/M0KidB8oWxE6EtWxeiDisLf3vkZPuR2tBhD51tP1TO5PbEePuJYm5d9bw3",
	"u6hSnQDtrOCyWzWk2nxgkPejLT5vcZ7BHz6/j8/v4J35AGCP/eRipJ8n4iaFT+J7AWe5CpiLCJiQbLZE",
	"MBvFrtbUH8feet20MfVHtBTRknl9V7SUl63O+VMdVa6Qr24mb0aj0yFPxPD+ZOitblf/DQAA//+BkCe1",
	"SjIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
