//go:build go1.22

// Package intern provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package intern

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// AdditionalInformation A map containing flexible metadata or contextual details about the error.
	AdditionalInformation *map[string]interface{} `json:"additionalInformation,omitempty"`

	// Code An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetails

// Forbidden defines model for Forbidden.
type Forbidden = ProblemDetails

// NotFound defines model for NotFound.
type NotFound = ProblemDetails

// ServerError defines model for ServerError.
type ServerError = ProblemDetails

// Unauthorized defines model for Unauthorized.
type Unauthorized = ProblemDetails

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ProblemDetails

// DownloadSolutionArchiveParams defines parameters for DownloadSolutionArchive.
type DownloadSolutionArchiveParams struct {
	// Range Range of the chunk to serve. Must respect the format `bytes=<start-index>-<end-index>`
	Range string `json:"Range"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DownloadSolutionArchive request
	DownloadSolutionArchive(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DescribeSolutionArchive request
	DescribeSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DownloadSolutionArchive(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadSolutionArchiveRequest(c.Server, solutionArchive, version, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DescribeSolutionArchive(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDescribeSolutionArchiveRequest(c.Server, solutionArchive, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDownloadSolutionArchiveRequest generates requests for DownloadSolutionArchive
func NewDownloadSolutionArchiveRequest(server string, solutionArchive string, version string, params *DownloadSolutionArchiveParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "solutionArchive", solutionArchive, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/downloads/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Range", params.Range, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Range", headerParam0)

	}

	return req, nil
}

// NewDescribeSolutionArchiveRequest generates requests for DescribeSolutionArchive
func NewDescribeSolutionArchiveRequest(server string, solutionArchive string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "solutionArchive", solutionArchive, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/downloads/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodHead, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DownloadSolutionArchiveWithResponse request
	DownloadSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*DownloadSolutionArchiveResponse, error)

	// DescribeSolutionArchiveWithResponse request
	DescribeSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DescribeSolutionArchiveResponse, error)
}

type DownloadSolutionArchiveResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON422 *UnprocessableEntity
	ApplicationproblemJSON500 *ServerError
}

// Status returns HTTPResponse.Status
func (r DownloadSolutionArchiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadSolutionArchiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DownloadSolutionArchiveResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DescribeSolutionArchiveResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON500 *ServerError
}

// Status returns HTTPResponse.Status
func (r DescribeSolutionArchiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DescribeSolutionArchiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DescribeSolutionArchiveResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DownloadSolutionArchiveWithResponse request returning *DownloadSolutionArchiveResponse
func (c *ClientWithResponses) DownloadSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, params *DownloadSolutionArchiveParams, reqEditors ...RequestEditorFn) (*DownloadSolutionArchiveResponse, error) {
	rsp, err := c.DownloadSolutionArchive(ctx, solutionArchive, version, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadSolutionArchiveResponse(rsp)
}

// DescribeSolutionArchiveWithResponse request returning *DescribeSolutionArchiveResponse
func (c *ClientWithResponses) DescribeSolutionArchiveWithResponse(ctx context.Context, solutionArchive string, version string, reqEditors ...RequestEditorFn) (*DescribeSolutionArchiveResponse, error) {
	rsp, err := c.DescribeSolutionArchive(ctx, solutionArchive, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDescribeSolutionArchiveResponse(rsp)
}

// ParseDownloadSolutionArchiveResponse parses an HTTP response from a DownloadSolutionArchiveWithResponse call
func ParseDownloadSolutionArchiveResponse(rsp *http.Response) (*DownloadSolutionArchiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadSolutionArchiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseDescribeSolutionArchiveResponse parses an HTTP response from a DescribeSolutionArchiveWithResponse call
func ParseDescribeSolutionArchiveResponse(rsp *http.Response) (*DescribeSolutionArchiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DescribeSolutionArchiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Download the solution archive.
	// (GET /downloads/{solutionArchive}/{version})
	DownloadSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string, params DownloadSolutionArchiveParams)
	// Describe the solution archive.
	// (HEAD /downloads/{solutionArchive}/{version})
	DescribeSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DownloadSolutionArchive operation middleware
func (siw *ServerInterfaceWrapper) DownloadSolutionArchive(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "solutionArchive" -------------
	var solutionArchive string

	err = runtime.BindStyledParameterWithOptions("simple", "solutionArchive", r.PathValue("solutionArchive"), &solutionArchive, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "solutionArchive", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadSolutionArchiveParams

	headers := r.Header

	// ------------- Required header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = Range

	} else {
		err := fmt.Errorf("Header parameter Range is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Range", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadSolutionArchive(w, r, solutionArchive, version, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DescribeSolutionArchive operation middleware
func (siw *ServerInterfaceWrapper) DescribeSolutionArchive(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "solutionArchive" -------------
	var solutionArchive string

	err = runtime.BindStyledParameterWithOptions("simple", "solutionArchive", r.PathValue("solutionArchive"), &solutionArchive, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "solutionArchive", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DescribeSolutionArchive(w, r, solutionArchive, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/downloads/{solutionArchive}/{version}", wrapper.DownloadSolutionArchive)
	m.HandleFunc(http.MethodHead+" "+options.BaseURL+"/downloads/{solutionArchive}/{version}", wrapper.DescribeSolutionArchive)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse ProblemDetails

type ForbiddenApplicationProblemPlusJSONResponse ProblemDetails

type NotFoundApplicationProblemPlusJSONResponse ProblemDetails

type ServerErrorApplicationProblemPlusJSONResponse ProblemDetails

type UnauthorizedApplicationProblemPlusJSONResponse ProblemDetails

type UnprocessableEntityApplicationProblemPlusJSONResponse ProblemDetails

type DownloadSolutionArchiveRequestObject struct {
	SolutionArchive string `json:"solutionArchive"`
	Version         string `json:"version"`
	Params          DownloadSolutionArchiveParams
}

type DownloadSolutionArchiveResponseObject interface {
	VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error
}

type DownloadSolutionArchive206ResponseHeaders struct {
	ContentDigest string
	ContentRange  string
}

type DownloadSolutionArchive206ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadSolutionArchive206ResponseHeaders
	ContentLength int64
}

func (response DownloadSolutionArchive206ApplicationoctetStreamResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Digest", fmt.Sprint(response.Headers.ContentDigest))
	w.Header().Set("Content-Range", fmt.Sprint(response.Headers.ContentRange))
	w.WriteHeader(206)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadSolutionArchive400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive400ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSolutionArchive401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive401ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSolutionArchive403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive403ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSolutionArchive404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive404ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSolutionArchive422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive422ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSolutionArchive500ApplicationProblemPlusJSONResponse struct {
	ServerErrorApplicationProblemPlusJSONResponse
}

func (response DownloadSolutionArchive500ApplicationProblemPlusJSONResponse) VisitDownloadSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DescribeSolutionArchiveRequestObject struct {
	SolutionArchive string `json:"solutionArchive"`
	Version         string `json:"version"`
}

type DescribeSolutionArchiveResponseObject interface {
	VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error
}

type DescribeSolutionArchive200ResponseHeaders struct {
	ContentLength int64
}

type DescribeSolutionArchive200Response struct {
	Headers DescribeSolutionArchive200ResponseHeaders
}

func (response DescribeSolutionArchive200Response) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.WriteHeader(200)
	return nil
}

type DescribeSolutionArchive400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive400ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DescribeSolutionArchive401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive401ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DescribeSolutionArchive403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive403ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DescribeSolutionArchive404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive404ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DescribeSolutionArchive500ApplicationProblemPlusJSONResponse struct {
	ServerErrorApplicationProblemPlusJSONResponse
}

func (response DescribeSolutionArchive500ApplicationProblemPlusJSONResponse) VisitDescribeSolutionArchiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Download the solution archive.
	// (GET /downloads/{solutionArchive}/{version})
	DownloadSolutionArchive(ctx context.Context, request DownloadSolutionArchiveRequestObject) (DownloadSolutionArchiveResponseObject, error)
	// Describe the solution archive.
	// (HEAD /downloads/{solutionArchive}/{version})
	DescribeSolutionArchive(ctx context.Context, request DescribeSolutionArchiveRequestObject) (DescribeSolutionArchiveResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DownloadSolutionArchive operation middleware
func (sh *strictHandler) DownloadSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string, params DownloadSolutionArchiveParams) {
	var request DownloadSolutionArchiveRequestObject

	request.SolutionArchive = solutionArchive
	request.Version = version
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadSolutionArchive(ctx, request.(DownloadSolutionArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadSolutionArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadSolutionArchiveResponseObject); ok {
		if err := validResponse.VisitDownloadSolutionArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DescribeSolutionArchive operation middleware
func (sh *strictHandler) DescribeSolutionArchive(w http.ResponseWriter, r *http.Request, solutionArchive string, version string) {
	var request DescribeSolutionArchiveRequestObject

	request.SolutionArchive = solutionArchive
	request.Version = version

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DescribeSolutionArchive(ctx, request.(DescribeSolutionArchiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DescribeSolutionArchive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DescribeSolutionArchiveResponseObject); ok {
		if err := validResponse.VisitDescribeSolutionArchiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptb9s4Ev4rBO8+XFHLVhwnbQX0Q7tNtsG2Rfp6QLcBQotji1uJVEkqiRP4vx9I6tWW/JrcAbfplyaS",
	"OPPMM8PhzDB3OBRJKjhwrXBwh+GGJGkM9ueJkGNGKXDzyxWJMzA/UNCExTjAXyJAEpTIZAgoFFlMERca",
	"jc1TnUkOFBGFtP3qVwZKC4mYst+QTEdCsluguIeVJjpTOBj5hz2smY4BB/i01N3DepaaR2QsMh2MY8J/",
	"4vm8hxm/IjGj3ljQmZdKkYLUM28iZEK0A6pCyVLNBMcB/gSpBAVcE/MAiQkiaOT76DWh6JPDZ6xJBVeA",
	"riOQgAgyolEhGlEBDn4MVyDJFKxxoZASQo1yxb2KqVBQg3vk+54/wr1F5pxOqyIUXBPGFSIoIbGRBLTU",
	"229w5FccnTkC0Gsj4rxAeVrgyGmLtE5VMBikUoxjSJQnYcqUlrO+SojUYyCyH4pksJLOdXx710xHHkgp",
	"pHrk/r/FfW1P7km3XsFKrrvyhVPbQfazDcnmpdymo63QLWn/lgO6F9adVWtIv/d4f3TACgfkFngREAry",
	"PlN8wY2TbEi4YhQouiaqygZdTB93Md2aUhZVEUkS0CDXUl1Af+sW7ptj2slcS/cDZPhfGcgZEoYLHVWE",
	"IFbjvv93IT9hSjE+be6FeyJa/sqYBIoujfDLaqubKBcJ0xooGs/yE5WrLAHZyfuLLt6N15wNJrfATQqh",
	"lVtPLp10v89XNr7enuZ2EjvpfYCYfqS6pLoZ6/fE76WTdllLF7tQO9yS2rdfvpwvJJG1BDc/353hBR67",
	"KX6AcH6ku43ukoz7YtmehJdISHRpzsJ96T7cku6Og3hjyis+9ma9ErWS+IcI9UcntDuBC+1NRMbpqjGQ",
	"XQi0GghdE9evu5V1G0aVDR9qH3RMeRTIK5DO1d0A3FcIeCgyrkECNdxmvGTXra9gHNWp/OxWn+TfdCDJ",
	"eG1s1YrkVRiCUkiLn8Ct8Qq08Whe/fVRB1etw7MGZwcV2K+8MT3rBJtKYdCQcQwecM30rB10PTQbbY9B",
	"3kCWS3RFeYltOKxjq2lFJ05rB8Z5Dxd70G7h14Tme9PtJK6B2x9JmsYstFu5iOSnfynBF8eVOcumMy0a",
	"09OyU/ynhAkO8D8G1bhzUCxeM37pdUv+N9PRSZmEdtbRyGbt+r4VfttBSd5Qd8vd24zlmUilLXeqa6C2",
	"dEhHu7RK9g62rO93q6Oozt1aBR01cquwLXCv72UqFQ2GNpa8WAO1i9sB8oqCdUnJeb3K2kp67fzqFLoH",
	"+PYqxB5WYQQJ6RLo3qrBuUtib2wGVi4VNguYXXIy+sF/8JMcs6l5Lmvlju1EjVLk8n5Z/qjALEMe+rO1",
	"L7z411794OCJk33WOml0G21zFatS6GpNNj/tq8gKGTxpstXsOranq7khFq1oSt+ZsNYE12VJGd27G1OK",
	"GDxBxb92w8ov97at2pTtAbGsccegWFaYB4ZJNqf1K9MdapjGlevKpFR9+UCJp+22FmmBUpCGYaQjppDZ",
	"GnmTxfM7DFfT9g0bH4Q+LRqHHcjgteUruag6lAfiorOxsWa69uGk6FB2sFQ1Jaw0ttEQ3be9G/ZR816z",
	"DdnN6sWGaqXZjY/v0+xG08ZUW9/m7K21NidlP7WT2a2S1ljf0s79ryuOGgBr2IKW4A7nZydzhhNKmVFH",
	"4jPukjQTvPnivLZAywyWnIUSkhZXPObUmsRww0yzmYAmlGji8HINNzojcV7uKGR7T5uhbASbDjYn17WO",
	"GqTBRXHw4vmz46OywzhlEFOFgz8xJKZf7uFblv4mKOAL0/YmoDRJUhzgoT889vwjb3jwxX8eHIwC3/+O",
	"52XvK8Z/QWhbFzcjWhxZveLo1fkZUimEbMJChxKZbxFh1FhqsOf3kxJpIAnKOAWpNOG0MgyNiQKaZ2Mm",
	"kbjmKBUmRBmJkSY3govEjpnKYw73cEJu3gGf6sgMRkrMSkvGp3hezbGWUKMoSwj3JBBqW364SWPC3YlQ",
	"2qJFfliEYSYl8BBMeZrbYyJmAcLIf3HcAoJxY2vYRh76+ukMSZiAk64johGjxugJA/c3SCWabhToTKOE",
	"WHLMfybeZ8b9aJJJHYHJB2XYIjZBFEqVdMGEA384ajGhGJrctew+O/N2Hzi/T4GDJLWRo5BsyniRoydC",
	"bkBrcVduQvxw6ECyJEtwcPTihWmOuPvtwK/8bnbD1DVP+WBnmXAVCal7i+5XWZIQOVvAgYxcy66KykwS",
	"RoRPAU2kSOoWaNFtTw/BTQip/XMflGYyFcp1OrEIScxurWM2c4R7sEscNWyqE5xJtoFqO/Vyd4QmqTh+",
	"L5bShLuOn4hljG/ENY8FoUiJODPPEJFhxK5AWVregybxH88VLn23xYorkMppOej7fd8QJVLgJGU4wId9",
	"v29m2mY8bUN4QHPBanBXiH7lJM8Hd7msuflyCvaALIvFM1qD9bm51GrIK2uTdxft/0CSMi4WDcKGNBxY",
	"iLiHOUks9UsKKg+4M6Y6RJe8taj+mzNrOwQFr3tp/mT3S643jDL+02wWmwz66H2WX2lA6E45F5bocjzT",
	"oF7+yHz/MFSaSO0xTuHGPgDPPQdO608v62cjdgJ8b1iYVt6v5cZZXFuZdrEw+R36xytKKRFq0J7SEkhi",
	"3lVyy603ZpzI2qC51LRU5qjMVnuTLEYpkfZMLNT2cssspN/cQ+8Nm+YD6eWETe27hkd66DVRcDyyBTQF",
	"upKWimMVEW94dPwyoKPDo4/iKf/j+9Ppu/DrW/7s94/647NhxF5/ezX9Jd6p7/z7Ofvy+/nPl0E9+Yyt",
	"WtyWbgpTnJ9aLZHLoWXjalP8NkaQ7w0HowYo+3ir2Bu4p1poEnuK3YLHuGfluPdtPp73zIVbVwlcRtqg",
	"dsFglxysX9Jocuyiw/WLqhmAXTFav6Lsk82C4XATXMstxLyHjzahod6t2gLendn1g6Its9kmyOyQlkxu",
	"A2oMj5l8w3TnL2/DWmIqyW1PSUV5sSjhM7st6azGFhMWA2Ic2T20Ena9UqynkrIa/H/bafvuljzqu3ZL",
	"dXntgj+Tce1K/uzcXEEPByRlg6uDAZ5fzP8zAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
